### ISSUE TITLE
Update tutorial URLs

### ISSUE THREAD

**Issue by maxim-h** [andygxzeng/BoneMarrowMap#1]
Hi, Andy! Thanks for the great work.

I noticed that the links to In-depth tutorial and Leukemia projection `Rmd` files seem to be broken. I get 404 error.

The links that **worked** for me are:

`https://raw.githubusercontent.com/andygxzeng/BoneMarrowMap_Extras/main/BoneMarrowMap_Tutorial.Rmd`

and

`https://raw.githubusercontent.com/andygxzeng/BoneMarrowMap_Extras/main/LeukemiaProjection_Tutorial.Rmd`

**Comment by andygxzeng** [comment]
Hi there - thanks so much for catching this, I've corrected the links
Appreciate it!
