### ISSUE TITLE
Using cca integration instead of harmony

### ISSUE THREAD

**Issue by 2019surbhi** [andygxzeng/BoneMarrowMap#7]
Can you provide gene expression matrix for this dataset or add an option to perform batch correction using Seurat's integrated.ccca method  instead of Harmony?  I process my dataset using integrated.cca batch correction. 

It makes sense that the ref and query needs to be processed the same way but when I project back the prediction to my UMAP, the predictions don't fit my UMAP structure and clustering very well.

**Comment by adhisadi** [comment]
> Can you provide gene expression matrix for this dataset or add an option to perform batch correction using Seurat's integrated.ccca method instead of Harmony? I process my dataset using integrated.cca batch correction.
> 
> It makes sense that the ref and query needs to be processed the same way but when I project back the prediction to my UMAP, the predictions don't fit my UMAP structure and clustering very well.

Hi,
Did you figure this out? How did you know the integration was performed using harmony for the reference dataset? I can't find that information anywhere.

**Comment by 2019surbhi** [comment]
No, I haven't.

**Comment by andygxzeng** [comment]
Hi there - sorry about the delayed response, I was waiting around some data concerns RE sharing of the gene expression matrix. 

I'm happy to share the rds object for the gene expression matrix if you email me at andy.zeng@uhn.ca. 

In the meantime, you can simply input the raw counts into the map_Query function in order to map your data. I have updated the package to store the projection results in a separate slot, so if you re-install it you can overlay the cell type annotations on the CCA corrected UMAP that you've constructed accordingly!

**Comment by adhisadi** [comment]
Hi, thank you for the reply. 
Could you elaborate? Do you mean we can do this?
DefaultAssay(seurat_obj) <- "RNA"
Then run the map query script.

**Comment by adhisadi** [comment]
> Hi, thank you for the reply.
> Could you elaborate? Do you mean we can do this?
> DefaultAssay(seurat_obj) <- "RNA"
> Then run the map query script.

Hi, thank you for the reply.
Could you elaborate? Do you mean we can do this?
DefaultAssay(seurat_obj) <- "RNA"
Then run the map query script.

**Comment by adhisadi** [comment]
> Hi there - sorry about the delayed response, I was waiting around some data concerns RE sharing of the gene expression matrix.
> 
> I'm happy to share the rds object for the gene expression matrix if you email me at [andy.zeng@uhn.ca](mailto:andy.zeng@uhn.ca).
> 
> In the meantime, you can simply input the raw counts into the map_Query function in order to map your data. I have updated the package to store the projection results in a separate slot, so if you re-install it you can overlay the cell type annotations on the CCA corrected UMAP that you've constructed accordingly!

Hi, thank you for the reply.
Could you elaborate? Do you mean we can do this?
DefaultAssay(seurat_obj) <- "RNA"
Then run the map query script.

**Comment by adhisadi** [comment]
> > Hi there - sorry about the delayed response, I was waiting around some data concerns RE sharing of the gene expression matrix.
> > I'm happy to share the rds object for the gene expression matrix if you email me at [andy.zeng@uhn.ca](mailto:andy.zeng@uhn.ca).
> > In the meantime, you can simply input the raw counts into the map_Query function in order to map your data. I have updated the package to store the projection results in a separate slot, so if you re-install it you can overlay the cell type annotations on the CCA corrected UMAP that you've constructed accordingly!
> 
> Hi, thank you for the reply. Could you elaborate? Do you mean we can do this? DefaultAssay(seurat_obj) <- "RNA" Then run the map query script.

This did not work though. I got
Error: matrix multiplication: incompatible matrix dimensions

**Comment by adhisadi** [comment]
> > > Hi there - sorry about the delayed response, I was waiting around some data concerns RE sharing of the gene expression matrix.
> > > I'm happy to share the rds object for the gene expression matrix if you email me at [andy.zeng@uhn.ca](mailto:andy.zeng@uhn.ca).
> > > In the meantime, you can simply input the raw counts into the map_Query function in order to map your data. I have updated the package to store the projection results in a separate slot, so if you re-install it you can overlay the cell type annotations on the CCA corrected UMAP that you've constructed accordingly!
> > 
> > 
> > Hi, thank you for the reply. Could you elaborate? Do you mean we can do this? DefaultAssay(seurat_obj) <- "RNA" Then run the map query script.
> 
> This did not work though. I got Error: matrix multiplication: incompatible matrix dimensions

I ended up joining layers and then it worked. 

seurat_obj[["RNA"]] <- JoinLayers(seurat_obj[["RNA"]])

counts <- LayerData(seurat_obj, assay = "RNA", layer = "counts")
metadata <- seurat_obj[[]]

query <-  map_Query(
  exp_query = counts,
  metadata_query = metadata,
  ref_obj = ref,
  vars = batchvar
)
